#
#
#services:
#
#  db:
#    image: postgres
#    container_name: db
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: Site
#      ports:
#        -"5432:5432"
#
#  my-app:
#    image: spring-service
#    container_name: spring-backend
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Site
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    depends_on:
#      - db
## .env
#
#
##  pgadmin:
##    container_name: pgadmin4_container
##    image: dpage/pgadmin4
##    restart: always
##    environment:
##      PGADMIN_DEFAULT_EMAIL: admin@admin.com
##      PGADMIN_DEFAULT_PASSWORD: postgres
##    ports:
##      - "5050:80"
#
#  my-py-service:
#    image: python-service
#    container_name: python-service
#    ports:
#      - "5000:5000"
#
##docker network
